import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import fs from 'fs';

export default defineConfig({
  plugins: [
    react(),
    // Enhanced redirects plugin with error handling
    {
      name: 'inject-redirects',
      apply: 'build',
      closeBundle() {
        try {
          const redirectsPath = resolve(__dirname, 'dist', '_redirects');
          fs.mkdirSync(resolve(__dirname, 'dist'), { recursive: true });
          fs.writeFileSync(
            redirectsPath,
            '# Auto-generated by Vite\n/* /index.html 200\n'
          );
          console.log('✓ _redirects file created successfully');
        } catch (err) {
          console.error('Error creating _redirects:', err);
        }
      }
    }
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:5050',
        changeOrigin: true,
        secure: false,
        rewrite: path => path.replace(/^\/api/, '')
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    chunkSizeWarningLimit: 1500, // Increased limit
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('react')) return 'vendor-react';
            if (id.includes('react-router')) return 'vendor-router';
            return 'vendor-other';
          }
        },
        chunkFileNames: 'assets/[name]-[hash].js'
      }
    }
  },
  base: './',
  // Cache busting for production
  esbuild: {
    drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : []
  }
});