import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import fs from 'fs';

export default defineConfig({
  plugins: [
    react(),
    {
      name: 'inject-redirects',
      apply: 'build',
      closeBundle() {
        try {
          const distPath = resolve(__dirname, 'dist');
          const redirectsPath = resolve(distPath, '_redirects');
          
          // Ensure dist directory exists
          if (!fs.existsSync(distPath)) {
            fs.mkdirSync(distPath, { recursive: true });
          }

          // Write redirects with explicit reset-password handling
          fs.writeFileSync(
            redirectsPath,
            '# Auto-generated by Vite\n' +
            '/* /index.html 200\n' +
            '/reset-password /index.html 200\n' +
            '/reset-password/* /index.html 200\n' +
            '!/assets/*\n' +
            '!/favicon.ico'
          );
          
          console.log('✓ _redirects file created with reset-password rules');
        } catch (err) {
          console.error('Error creating _redirects:', err);
          process.exit(1); // Fail build on error
        }
      }
    }
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:5050',
        changeOrigin: true,
        secure: false,
        rewrite: path => path.replace(/^\/api/, '')
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    chunkSizeWarningLimit: 1500,
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('react')) return 'vendor-react';
            if (id.includes('react-router')) return 'vendor-router';
            return 'vendor-other';
          }
        },
        chunkFileNames: 'assets/[name]-[hash].js'
      }
    }
  },
  base: './',
  esbuild: {
    drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : []
  }
});